#!/bin/sh

#   siena - Structural Image Evaluation, including Normalisation, of Atrophy
#
#   Stephen Smith, FMRIB Image Analysis Group
#
#   Copyright (C) 1999-2007 University of Oxford
#
#   Part of FSL - FMRIB's Software Library
#   http://www.fmrib.ox.ac.uk/fsl
#   fsl@fmrib.ox.ac.uk
#   
#   Developed at FMRIB (Oxford Centre for Functional Magnetic Resonance
#   Imaging of the Brain), Department of Clinical Neurology, Oxford
#   University, Oxford, UK
#   
#   
#   LICENCE
#   
#   FMRIB Software Library, Release 5.0 (c) 2012, The University of
#   Oxford (the "Software")
#   
#   The Software remains the property of the University of Oxford ("the
#   University").
#   
#   The Software is distributed "AS IS" under this Licence solely for
#   non-commercial use in the hope that it will be useful, but in order
#   that the University as a charitable foundation protects its assets for
#   the benefit of its educational and research purposes, the University
#   makes clear that no condition is made or to be implied, nor is any
#   warranty given or to be implied, as to the accuracy of the Software,
#   or that it will be suitable for any particular purpose or for use
#   under any specific conditions. Furthermore, the University disclaims
#   all responsibility for the use which is made of the Software. It
#   further disclaims any liability for the outcomes arising from using
#   the Software.
#   
#   The Licensee agrees to indemnify the University and hold the
#   University harmless from and against any and all claims, damages and
#   liabilities asserted by third parties (including claims for
#   negligence) which arise directly or indirectly from the use of the
#   Software or the sale of any products based on the Software.
#   
#   No part of the Software may be reproduced, modified, transmitted or
#   transferred in any form or by any means, electronic or mechanical,
#   without the express permission of the University. The permission of
#   the University is not required if the said reproduction, modification,
#   transmission or transference is done without financial return, the
#   conditions of this Licence are imposed upon the receiver of the
#   product, and all original and amended source code is included in any
#   transmitted product. You may be held legally responsible for any
#   copyright infringement that is caused or encouraged by your failure to
#   abide by these terms and conditions.
#   
#   You are not permitted under this Licence to use this Software
#   commercially. Use for which any financial return is received shall be
#   defined as commercial use, and includes (1) integration of all or part
#   of the source code or the Software into a product for sale or license
#   by or on behalf of Licensee to third parties or (2) use of the
#   Software or any derivative of it for research with the final aim of
#   developing software products for sale or license to a third party or
#   (3) use of the Software or any derivative of it for research with the
#   final aim of developing non-software products for sale or license to a
#   third party, or (4) use of the Software to provide any service to an
#   external organisation for which payment is received. If you are
#   interested in using the Software commercially, please contact Isis
#   Innovation Limited ("Isis"), the technology transfer company of the
#   University, to negotiate a licence. Contact details are:
#   innovation@isis.ox.ac.uk quoting reference DE/9564.

Usage() {
    cat <<EOF

Usage: siena <input1> <input2> [options]

  -o <output-dir>       : set output directory (default output is <input1>_to_<input2>_siena)
  -d                    : debug (don't delete intermediate files)
  -bm1                  : input brain mask for first t1
  -bm2                  : input brain mask for sedonc t1
  -B "betopts"          : options to pass to BET brain extraction (inside double-quotes), e.g. -B "-f 0.3"
  -2                    : two-class segmentation (don't segment grey and white matter separately)
  -t2                   : T2-weighted input image (default T1-weighted)
  -m                    : use standard-space masking as well as BET
  -t <t>                : ignore from t (mm) upwards in MNI152/Talairach space
  -b <b>                : ignore from b (mm) downwards in MNI152/Talairach space (b should probably be negative)
  -S "sienadiffopts"    : options to pass to siena_diff timepoint differencing (inside double-quotes), e.g. -S "-s -i 20"
  -V                    : run ventricle analysis (VIENA)
  -v <mask image>       : optional user-supplied ventricle mask (default is $FSLDIR/bin/MNI152_T1_2mm_VentricleMask)

EOF
    exit 1
}

[ "$2" = "" ] && Usage
[ `${FSLDIR}/bin/imtest $1` = 0 ] && Usage
[ `${FSLDIR}/bin/imtest $2` = 0 ] && Usage
Ao=`${FSLDIR}/bin/remove_ext $1`
Bo=`${FSLDIR}/bin/remove_ext $2`
thecommand="siena $@"
shift 2

outdir=${Ao}_to_${Bo}_siena
vienadir=${outdir}/viena
debug=0
bm1=""
bm2=""
sdopts=""
sdo="-m"
dostd=0
stdmask=0
stdroi=""
origin3=37 # `fslval ${FSLDIR}/data/standard/MNI152_T1_2mm origin3`
pixdim3=2  # `fslval ${FSLDIR}/data/standard/MNI152_T1_2mm pixdim3`
Vmask="${FSLDIR}/data/standard/MNI152_T1_2mm_VentricleMask"
do_viena=no

while [ _$1 != _ ] ; do

    if [ $1 = -d ] ; then
        debug=1
        ov=-ov
        shift
    elif [ $1 = -o ] ; then
        outdir=$2
	vienadir=${outdir}/viena
        shift 2
    elif [ $1 = -bm1 ] ; then
        bm1=$2
        shift 2
    elif [ $1 = -bm2 ] ; then
        bm2=$2
        shift 2
    elif [ $1 = -S ] ; then
        sdopts=$2
        shift 2
    elif [ $1 = -2 ] ; then
	sdo="$sdo -2"
        shift
    elif [ $1 = -t2 ] ; then
	is_t2=" -s -t 2"
        shift
    elif [ $1 = -m ] ; then
	stdmask=1
	dostd=1
        shift
    elif [ $1 = -t ] ; then
	dostd=1
	stdt=`echo $2 | sed 's/-/_/g'`
	stdt=`echo "10 k $stdt $pixdim3 / $origin3 + p" | dc -`
	stdroi="$stdroi -roi 0 1000000 0 1000000 0 $stdt 0 1"
	shift 2
    elif [ $1 = -b ] ; then
	dostd=1
	stdb=`echo $2 | sed 's/-/_/g'`
	stdb=`echo "10 k $stdb $pixdim3 / $origin3 + p" | dc -`
	stdroi="$stdroi -roi 0 1000000 0 1000000 $stdb 1000000 0 1"
	shift 2
    elif [ $1 = -V ] ; then
        do_viena=yes
        shift
    elif [ $1 = -v ] ; then
        Vmask=$2
        shift 2
    else
	Usage
    fi

done

# ensure full path for ventriclemask (because of cd in scripts)
if [ $do_viena = yes ] ; then
    if [ `${FSLDIR}/bin/imtest ${Vmask}` = 0 ] ; then
	echo "ERROR:: cannot find image ${Vmask}"
	Usage
    fi
fi

sdo="${sdo}${is_t2}"

mkdir -p $outdir
if [ $do_viena = yes ] ; then 
  mkdir -p $vienadir
fi
${FSLDIR}/bin/imcp $Ao ${outdir}/A
${FSLDIR}/bin/imcp $Bo ${outdir}/B
cd $outdir
A=A
B=B

echo '<HTML><HEAD><link REL="stylesheet" TYPE="text/css" href="file:'${FSLDIR}'/doc/fsl.css"><TITLE>FSL</TITLE></HEAD><BODY><hr><TABLE BORDER=0 WIDTH="100%"><TR><TD ALIGN=CENTER><H1>SIENA Report</H1>'${thecommand}'<TD ALIGN=RIGHT><a href="'${FSLDIR}'/doc/index.html"><IMG BORDER=0 SRC="'${FSLDIR}'/doc//images/fsl-logo.jpg"></a></TR></TABLE>' > report.html

echo "-----------------------------------------------------------------------" >  report.siena
echo ""                                                                        >> report.siena
echo " SIENA - Structural Image Evaluation, using Normalisation, of Atrophy"   >> report.siena
echo " part of FSL www.fmrib.ox.ac.uk/fsl"                                     >> report.siena
echo " running longitudinal atrophy measurement: siena version 2.6"            >> report.siena
echo " siena $@"                                                               >> report.siena
echo ""                                                                        >> report.siena

echo "----------  extract brain  --------------------------------------------" >> report.siena
#Ao is full path T1A is T1 name
echo ${Ao}
remainderA="${Ao}"
T1A=${remainderA##*/}
echo "T1_tp1" ${T1A}
echo "T1_tp2" ${T1B}

echo ${Bo}
remainderB="${Bo}"
T1B=${remainderB##*/}
echo "T1_tp2" $T1B

echo "Brain Mask tp1" ${bm1}
echo "Brain Mask tp2" ${bm2}
echo ${bm1}_brain_skull

echo $outdir

echo "************************"
echo $A "$A"
echo $Ao "$Ao"
echo ${Ao} "${Ao}"
echo $T1A "T1A"
echo ${T1A} "${T1A}"
echo $bm1 "$bm1"
echo ${bm1} "${bm1}"
echo "************************"

${FSLDIR}/bin/bet $A ${T1A}_brain -s -m $betopts >> report.siena
${FSLDIR}/bin/bet $B ${T1B}_brain -s -m $betopts >> report.siena
${FSLDIR}/bin/fslmaths ${T1A}_brain -sub `$FSLDIR/bin/fslstats ${T1A}_brain -p 0` -mas ${T1A}_brain_mask ${T1A}_brain -odt float
${FSLDIR}/bin/fslmaths ${T1B}_brain -sub `$FSLDIR/bin/fslstats ${T1B}_brain -p 0` -mas ${T1B}_brain_mask ${T1B}_brain -odt float

echo ${FSLDIR}/bin/bet ${Ao} ${Ao}_brain -s -m $betopts >> report.siena
${FSLDIR}/bin/bet ${Ao} ${Ao}_brain -s -m $betopts >> report.siena
${FSLDIR}/bin/bet ${Bo} ${Bo}_brain -s -m $betopts >> report.siena
echo ${FSLDIR}/bin/fslmaths ${Ao}_brain -sub `$FSLDIR/bin/fslstats ${Ao}_brain -p 0` -mas ${Ao}_brain_mask ${Ao}_brain -odt float
${FSLDIR}/bin/fslmaths ${Ao}_brain -sub `$FSLDIR/bin/fslstats ${Ao}_brain -p 0` -mas ${Ao}_brain_mask ${Ao}_brain -odt float
${FSLDIR}/bin/fslmaths ${Bo}_brain -sub `$FSLDIR/bin/fslstats ${Bo}_brain -p 0` -mas ${Bo}_brain_mask ${Bo}_brain -odt float

echo "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

echo ${FSLDIR}/bin/fslmaths $bm1 -mul ${Ao}.nii.gz ${T1A}_brain
${FSLDIR}/bin/fslmaths $bm1 -mul ${Ao}.nii.gz ${T1A}_brain
echo ${FSLDIR}/bin/fslmaths $bm1 -mul 1 ${T1A}_brain_mask
${FSLDIR}/bin/fslmaths $bm1 -mul 1 ${T1A}_brain_mask


#echo ${FSLDIR}/bin/fslmaths $bm2 -mul ${Bo}.nii.gz ${T1B}_brain
#echo ${FSLDIR}/bin/fslmaths $bm2 -mul 1 ${T1B}_brain_mask
#${FSLDIR}/bin/fslmaths $bm2 -mul ${Bo}.nii.gz {$T1B}_brain
#${FSLDIR}/bin/fslmaths $bm2 -mul 1 ${T1B}_brain_mask

echo "NEXT SECTION"

${FSLDIR}/bin/overlay 0 0 $Ao -a ${T1A}_brain 1 `${FSLDIR}/bin/fslstats ${T1A}_brain -P 95` ${T1A}_brain_skull 0.9 1.1 ${T1A}_grot
${FSLDIR}/bin/slicer ${T1A}_grot -a ${T1A}_bet.png
${FSLDIR}/bin/overlay 0 0 $Bo -a ${T1B}_brain 1 `${FSLDIR}/bin/fslstats ${T1B}_brain -P 95` ${T1B}_brain_skull 0.9 1.1 ${T1B}_grot
${FSLDIR}/bin/slicer ${T1B}_grot -a ${T1B}_bet.png
${FSLDIR}/bin/imrm ${T1A}_grot ${T1B}_grot
echo "<hr><p><b>BET brain extraction results</b><p>${T1A}<br><IMG BORDER=0 SRC=\"${T1A}_bet.png\"><p>${Bo}<br><IMG BORDER=0 SRC=\"${T1B}_bet.png\">" >> report.html


echo "&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&"


echo ""                                                                        >> report.siena
echo "----------  register brains and skulls  -------------------------------" >> report.siena
echo "(do not worry about histogram warnings)"                                 >> report.siena
${FSLDIR}/bin/siena_flirt $A $B >> report.siena 2>&1
echo "<hr><p><b>FLIRT A-to-B registration results</b><p><IMG BORDER=0 SRC=\"${T1A}_and_${T1B}.gif\">" >> report.html

echo ""                                                                        >> report.siena
echo "----------  produce valid masks  --------------------------------------" >> report.siena
T1A=${remainderA##*/}
T1B=${remainderB##*/}

XDIM=`${FSLDIR}/bin/fslval $A dim1` ; XDIM=`echo "$XDIM 2 - p" | dc -`
YDIM=`${FSLDIR}/bin/fslval $A dim2` ; YDIM=`echo "$YDIM 2 - p" | dc -`
ZDIM=`${FSLDIR}/bin/fslval $A dim3` ; ZDIM=`echo "$ZDIM 2 - p" | dc -`
${FSLDIR}/bin/fslmaths $T1A_brain_mask -mul 0 -add 1 -roi 1 $XDIM 1 $YDIM 1 $ZDIM 0 1 $T1A_valid_mask
XDIM=`${FSLDIR}/bin/fslval $B dim1` ; XDIM=`echo "$XDIM 2 - p" | dc -`
YDIM=`${FSLDIR}/bin/fslval $B dim2` ; YDIM=`echo "$YDIM 2 - p" | dc -`
ZDIM=`${FSLDIR}/bin/fslval $B dim3` ; ZDIM=`echo "$ZDIM 2 - p" | dc -`
${FSLDIR}/bin/fslmaths $T1B_brain_mask -mul 0 -add 1 -roi 1 $XDIM 1 $YDIM 1 $ZDIM 0 1 $T1B_valid_mask
${FSLDIR}/bin/flirt -in $T1B_valid_mask -ref $A -out $T1B_valid_mask_to_$T1A -applyxfm -init $T1B_to_$T1A.mat -paddingsize 0
${FSLDIR}/bin/flirt -in $T1A_valid_mask -ref $B -out $T1A_valid_mask_to_$T1B -applyxfm -init $T1A_to_$T1B.mat -paddingsize 0
${FSLDIR}/bin/fslmaths $T1A_valid_mask -mul $T1B_valid_mask_to_$T1A $T1A_valid_mask_with_$B
${FSLDIR}/bin/fslmaths $T1B_valid_mask -mul $T1A_valid_mask_to_$T1B $T1B_valid_mask_with_$A

if [ $dostd = 1 ] ; then
    echo ""                                                                        >> report.siena
    echo "----------  standard space masking  ----------------------------------" >> report.siena
    ${FSLDIR}/bin/flirt -ref ${FSLDIR}/data/standard/MNI152_T1_2mm_brain -in $T1A_brain -o $T1A_to_std -omat $T1A_to_std.mat >> report.siena
    ${FSLDIR}/bin/flirt -ref ${FSLDIR}/data/standard/MNI152_T1_2mm_brain -in $T1B_brain -o $T1B_to_std -omat $T1B_to_std.mat >> report.siena
    ${FSLDIR}/bin/convert_xfm -inverse -omat $T1A_to_std_inv.mat $T1A_to_std.mat
    ${FSLDIR}/bin/convert_xfm -inverse -omat $T1B_to_std_inv.mat $T1B_to_std.mat
    ${FSLDIR}/bin/slicer $T1A_to_std ${FSLDIR}/data/standard/MNI152_T1_2mm_brain -a $T1A_to_std.png
    ${FSLDIR}/bin/slicer $T1B_to_std ${FSLDIR}/data/standard/MNI152_T1_2mm_brain -a $T1B_to_std.png
    echo "<hr><p><b>FLIRT standard space registration results</b><p>$T1A<br><IMG BORDER=0 SRC=\"$T1A_to_std.png\"><p>${Bo}<br><IMG BORDER=0 SRC=\"$T1B_to_std.png\">" >> report.html

    ${FSLDIR}/bin/convert_xfm -concat $T1B_to_std_inv.mat -omat $T1A_to_$T1B_tmp.mat $T1A_to_std.mat
    RMSDIFF=`${FSLDIR}/bin/rmsdiff $T1A_to_$T1B.mat $T1A_to_$T1B_tmp.mat $A | sed 's/\..*$/ /g'` # last part makes it integer
    echo "rmsdiff for standard space transform is $RMSDIFF mm" >> report.siena
    if [ $RMSDIFF -ge 10 ] ; then
	echo "Warning! Probably failed consistency check for standard-space registrations!"
	echo "Warning! Probably failed consistency check for standard-space registrations!" >> report.siena
    fi

    if [ $stdmask = 1 ] ; then
	${FSLDIR}/bin/flirt -in ${FSLDIR}/data/standard/MNI152_T1_2mm_brain_mask_dil -ref $A -out $T1A_stdmask -applyxfm -init $T1A_to_std_inv.mat
	${FSLDIR}/bin/flirt -in ${FSLDIR}/data/standard/MNI152_T1_2mm_brain_mask_dil -ref $B -out $T1B_stdmask -applyxfm -init $T1B_to_std_inv.mat
	${FSLDIR}/bin/fslmaths $T1A_stdmask -thr 0.5 -bin $T1A_stdmask
	${FSLDIR}/bin/fslmaths $T1B_stdmask -thr 0.5 -bin $T1B_stdmask
	${FSLDIR}/bin/fslmaths $T1A_brain_mask -mas $T1A_stdmask $T1A_brain_mask
	${FSLDIR}/bin/fslmaths $T1B_brain_mask -mas $T1B_stdmask $T1B_brain_mask
    fi

    if [ "$stdroi" != "" ] ; then
	${FSLDIR}/bin/fslmaths ${FSLDIR}/data/standard/MNI152_T1_2mm_brain_mask -mul 0 -add 1 $stdroi $T1A_and_$T1B_stdmask
	${FSLDIR}/bin/flirt -in $T1A_and_$T1B_stdmask -ref $A -out $T1A_stdmask -applyxfm -init $T1A_to_std_inv.mat
	${FSLDIR}/bin/flirt -in $T1A_and_$T1B_stdmask -ref $B -out $T1B_stdmask -applyxfm -init $T1B_to_std_inv.mat
	${FSLDIR}/bin/fslmaths $T1A_stdmask -thr 0.5 -bin $T1A_stdmask
	${FSLDIR}/bin/fslmaths $T1B_stdmask -thr 0.5 -bin $T1B_stdmask
	${FSLDIR}/bin/fslmaths $T1A_valid_mask_with_$B -mul $T1A_stdmask $T1A_valid_mask_with_$B
	${FSLDIR}/bin/fslmaths $T1B_valid_mask_with_$A -mul $T1B_stdmask $T1B_valid_mask_with_$A
    fi
fi
${FSLDIR}/bin/overlay 0 0 -c $A -a $T1A_valid_mask_with_$B 0.9 3 $T1A_brain_mask 0.9 1.1 $T1A_valid_mask_with_$T1B_grot
${FSLDIR}/bin/slicer $T1A_valid_mask_with_$T1B_grot -a ${bm1}_valid_mask_with_$T1B.png
${FSLDIR}/bin/overlay 0 0 -c $B -a ${Bo}_valid_mask_with_$A 0.9 3 ${Bo}_brain_mask 0.9 1.1 ${Bo}_valid_mask_with_${bm1}_grot
${FSLDIR}/bin/slicer ${Bo}_valid_mask_with_${bm1}_grot -a ${Bo}_valid_mask_with_${bm1}.png
${FSLDIR}/bin/imrm ${bm1}_valid_mask_with_${Bo}_grot ${Bo}_valid_mask_with_${bm1}_grot
echo "<hr><p><b>Field-of-view and standard space masking</b><br>Red shows the common field-of-view of the two timepoint images and the standard-space-based field-of-view masking (if this was run). Blue shows the brain masks, including standard-space-based brain masking (if this was run). Green shows the intersection of the two.<p>$T1A<br><IMG BORDER=0 SRC=\"${bm1}_valid_mask_with_${Bo}.png\"><p>${Bo}<br><IMG BORDER=0 SRC=\"${Bo}_valid_mask_with_${bm1}.png\">" >> report.html

echo ""                                                                        >> report.siena
echo "----------  change analysis  ------------------------------------------" >> report.siena
corr1=`${FSLDIR}/bin/siena_cal $A $B 1.002 $sdo $sdopts`
corr2=`${FSLDIR}/bin/siena_cal $B $A 1.002 $sdo $sdopts`
corr=`echo "10 k $corr1 $corr2 + 2.0 / p" | dc -`
echo "corr1=$corr1 corr2=$corr2 corr=$corr" >> report.siena

echo "" >> report.siena
${FSLDIR}/bin/siena_diff ${Bo} ${bm1} -c $corr $sdo $sdopts >> report.siena
pbvc_backward=`grep PBVC report.siena | tail -n 1 | awk '{print $2}' | sed 's/-/_/g'`
${FSLDIR}/bin/overlay 1 0 -c ${Bo}_halfwayto_${bm1} -a ${Bo}_halfwayto_${bm1}_brain_seg 1.1 3 ${Bo}_halfwayto_${bm1}_brain_seg_grot
${FSLDIR}/bin/slicer ${Bo}_halfwayto_${bm1}_brain_seg_grot -a ${Bo}_halfwayto_${bm1}_brain_seg.png
${FSLDIR}/bin/imrm ${Bo}_halfwayto_${bm1}_brain_seg_grot

echo "" >> report.siena
${FSLDIR}/bin/siena_diff ${bm1} ${Bo} -c $corr $sdo $sdopts >> report.siena
${FSLDIR}/bin/overlay 1 0 -c ${bm1}_halfwayto_${Bo} -a ${bm1}_halfwayto_${Bo}_brain_seg 1.1 3 ${bm1}_halfwayto_${Bo}_brain_seg_grot
${FSLDIR}/bin/slicer ${bm1}_halfwayto_${Bo}_brain_seg_grot -a ${bm1}_halfwayto_${Bo}_brain_seg.png
${FSLDIR}/bin/imrm ${bm1}_halfwayto_${Bo}_brain_seg_grot
pbvc_forward=`grep PBVC report.siena | tail -n 1 | awk '{print $2}' | sed 's/-/_/g'`
echo "<hr><p><b>FAST tissue segmentation</b><br>These images show the tissue segmentation used to find the brain/non-brain boundary. The exact segmentation of grey matter vs. white matter is not important.<p>$T1A<br><IMG BORDER=0 SRC=\"${bm1}_halfwayto_${Bo}_brain_seg.png\"><p>${Bo}<br><IMG BORDER=0 SRC=\"${Bo}_halfwayto_${bm1}_brain_seg.png\">" >> report.html

echo "" >> report.siena
pbvc_average=`echo "10 k $pbvc_forward $pbvc_backward - 2.0 / p" | dc -`
echo "finalPBVC $pbvc_average %" >> report.siena

${FSLDIR}/bin/fslmaths ${bm1}_to_${Bo}_flow -mul -1 ${bm1}_to_${Bo}_flowneg
${FSLDIR}/bin/overlay 0 0 ${bm1}_halfwayto_${Bo} -a ${bm1}_to_${Bo}_flow 0.01 1 ${bm1}_to_${Bo}_flowneg 0.01 1 ${bm1}_halfwayto_${Bo}_render
${FSLDIR}/bin/slicer ${bm1}_halfwayto_${Bo}_render -s 1 -x 0.4 gr${bm1}_halfwayto_${Bo}a.png -x 0.5 gr${bm1}_halfwayto_${Bo}b.png -x 0.6 gr${bm1}_halfwayto_${Bo}c.png -y 0.4 gr${bm1}_halfwayto_${Bo}d.png -y 0.5 gr${bm1}_halfwayto_${Bo}e.png -y 0.6 gr${bm1}_halfwayto_${Bo}f.png -z 0.4 gr${bm1}_halfwayto_${Bo}g.png -z 0.5 gr${bm1}_halfwayto_${Bo}h.png -z 0.6 gr${bm1}_halfwayto_${Bo}i.png
${FSLDIR}/bin/pngappend gr${bm1}_halfwayto_${Bo}a.png + gr${bm1}_halfwayto_${Bo}b.png + gr${bm1}_halfwayto_${Bo}c.png + gr${bm1}_halfwayto_${Bo}d.png + gr${bm1}_halfwayto_${Bo}e.png + gr${bm1}_halfwayto_${Bo}f.png + gr${bm1}_halfwayto_${Bo}g.png + gr${bm1}_halfwayto_${Bo}h.png + gr${bm1}_halfwayto_${Bo}i.png ${bm1}_halfwayto_${Bo}_render.png
/bin/rm gr${bm1}_halfwayto_${Bo}?.???
/bin/cp ${FSLDIR}/etc/luts/ramp.gif .ramp.gif
/bin/cp ${FSLDIR}/etc/luts/ramp2.gif .ramp2.gif
echo "<hr><p><b>Final brain edge movement image</b><p>atrophy <IMG SRC=\".ramp2.gif\"> 0 <IMG SRC=\".ramp.gif\"> \"growth\"<p><IMG BORDER=0 SRC=\"${bm1}_halfwayto_${Bo}_render.png\"><p><b>Estimated PBVC: $pbvc_average</b>" >> report.html

if [ $do_viena = yes ] ; then
    ${FSLDIR}/bin/viena_quant ${bm1} ${Bo} ${vienadir}
fi


if [ $debug = 0 ] ; then
    T1A=${remainderA##*/}
    T1B=${remainderB##*/}
    $FSLDIR/bin/imrm \
	$T1A_brain $T1A_brain_mask $T1A_brain_skull \
	$T1B_brain $T1B_brain_mask $T1B_brain_skull \
	$T1A_halfwayto_$T1B $T1A_halfwayto_$T1B_mask \
	$T1B_halfwayto_$T1A $T1B_halfwayto_$T1A_mask \
	$T1A_halfwayto_$T1B_stdmask \
	$T1B_halfwayto_$T1A_stdmask \
	$T1A_halfwayto_$T1B_brain \
	$T1A_to_std $T1B_to_std \
	$T1A_halfwayto_$T1B_brain_seg \
	$T1A_to_$T1B_flowneg \
	$T1B_halfwayto_$T1A_brain \
	$T1B_halfwayto_$T1A_brain_seg \
	$T1B_to_$T1A_flowneg \
	$T1A_stdmask $T1B_stdmask \
	$T1A_and_$T1B_stdmask \
	$T1A_valid_mask $T1B_valid_mask $T1A_valid_mask_to_$T1B $T1B_valid_mask_to_$T1A \
	$T1A_valid_mask_with_$B $T1B_valid_mask_with_$A $T1A_halfwayto_$T1B_valid_mask $T1B_halfwayto_$T1A_valid_mask
    /bin/rm -f $T1A_to_$T1B_tmp.mat $T1A_halfwayto_$T1B_brain.vol $T1B_halfwayto_$T1A_brain.vol $T1B_to_$T1A.mat_avscale
fi

if [ $do_viena = yes ] && [ $debug = 0 ] ; then
    T1A=${remainderA##*/}
    T1B=${remainderB##*/}

    $FSLDIR/bin/imrm \
    $T1A_halfwayto_sc$T1A_brain \
    $T1A_to_sc$T1A_flow $T1A_to_sc$T1A_flow_ventricles \
    $T1A_to_sc$T1A_edgepoints $T1A_to_sc$T1A_edgepoints_ventricles \
    $T1A_halfwayto_sc$T1A_brain_ventricle_region_bin \
    $T1B_halfwayto_sc$T1B_brain \
    $T1B_to_sc$T1B_flow $T1B_to_sc$T1B_flow_ventricles \
    $T1B_to_sc$T1B_edgepoints $T1B_to_sc$T1B_edgepoints_ventricles \
    $T1B_halfwayto_sc$T1B_brain_ventricle_region_bin \
    $T1A_to_$T1B_edgepoints $T1A_to_$T1B_edgepoints_ventricles \
    $T1B_to_$T1A_edgepoints $T1B_to_$T1A_edgepoints_ventricles \
    $T1A_halfwayto_$T1B_ventricle_region_bin \
    $T1B_halfwayto_$T1A_ventricle_region_bin

fi



echo ""
echo "Finished. The SIENA report can be viewed by pointing your web browser at:"
echo file:`pwd`/report.html
echo "Estimated percentage brain volume change (PBVC) = "
echo "$pbvc_average"
echo ""

cat >> report.html <<EOF

<hr><p><b>SIENA Methods</b>

<p>Two-timepoint percentage brain volume change was estimated with
SIENA [Smith 2001, Smith 2002], part of FSL [Smith 2004]. SIENA starts
by extracting brain and skull images from the two-timepoint whole-head
input data [Smith 2002b]. The two brain images are then aligned to
each other [Jenkinson 2001, Jenkinson 2002] (using the skull images to
constrain the registration scaling); both brain images are resampled
into the space halfway between the two. Next, tissue-type segmentation
is carried out [Zhang 2001] in order to find brain/non-brain edge
points, and then perpendicular edge displacement (between the two
timepoints) is estimated at these edge points. Finally, the mean edge
displacement is converted into a (global) estimate of percentage brain
volume change between the two timepoints.

<font size=-1><em>
<P>[Smith 2001] S.M. Smith, N.&nbsp;De&nbsp;Stefano, M.&nbsp;Jenkinson, and P.M. Matthews.
<BR>&nbsp;&nbsp;&nbsp;Normalised accurate measurement of longitudinal brain change.
<BR>&nbsp;&nbsp;&nbsp;Journal of Computer Assisted Tomography, 25(3):466-475, May/June 2001.

<P>[Smith 2002] S.M. Smith, Y.&nbsp;Zhang, M.&nbsp;Jenkinson, J.&nbsp;Chen, P.M. Matthews, A.&nbsp;Federico, and N.&nbsp;De&nbsp;Stefano.
<BR>&nbsp;&nbsp;&nbsp;Accurate, robust and automated longitudinal and cross-sectional brain change analysis.
<BR>&nbsp;&nbsp;&nbsp;NeuroImage, 17(1):479-489, 2002.

<P>[Smith 2004] S.M. Smith, M.&nbsp;Jenkinson, M.W. Woolrich, C.F. Beckmann, T.E.J. Behrens, H.&nbsp;Johansen-Berg, P.R. Bannister, M.&nbsp;De&nbsp;Luca, I.&nbsp;Drobnjak, D.E. Flitney, R.&nbsp;Niazy, J.&nbsp;Saunders, J.&nbsp;Vickers, Y.&nbsp;Zhang, N.&nbsp;De&nbsp;Stefano, J.M. Brady, and P.M. Matthews.
<BR>&nbsp;&nbsp;&nbsp;Advances in functional and structural MR image analysis and
  implementation as FSL.
<BR>&nbsp;&nbsp;&nbsp;NeuroImage, 23(S1):208-219, 2004.

<P>[Smith 2002b] S.M. Smith.
<BR>&nbsp;&nbsp;&nbsp;Fast robust automated brain extraction.
<BR>&nbsp;&nbsp;&nbsp;Human Brain Mapping, 17(3):143-155, November 2002.

<P>[Jenkinson 2001] M.&nbsp;Jenkinson and S.M. Smith.
<BR>&nbsp;&nbsp;&nbsp;A global optimisation method for robust affine registration of brain images.
<BR>&nbsp;&nbsp;&nbsp;Medical Image Analysis, 5(2):143-156, June 2001.

<P>[Jenkinson 2002] M.&nbsp;Jenkinson, P.R. Bannister, J.M. Brady, and S.M. Smith.
<BR>&nbsp;&nbsp;&nbsp;Improved optimisation for the robust and accurate linear registration and motion correction of brain images.
<BR>&nbsp;&nbsp;&nbsp;NeuroImage, 17(2):825-841, 2002.

<P>[Zhang 2001] Y.&nbsp;Zhang, M.&nbsp;Brady, and S.&nbsp;Smith.
<BR>&nbsp;&nbsp;&nbsp;Segmentation of brain MR images through a hidden Markov random field model and the expectation maximization algorithm.
<BR>&nbsp;&nbsp;&nbsp;IEEE Trans. on Medical Imaging, 20(1):45-57, 2001.

EOF

